#pragma once
#include <string>
#include <iostream>
#include <fstream>
#include <map>
#include <algorithm>
#include <sstream>
#include <cctype>
#include <set>
#include <iomanip>
using std::string;
using std::map;
using std::isalpha;
using std::tolower;
using std::ifstream;
using std::cout;
using std::endl;
using std::ofstream;
using std::ispunct;
using std::set;